"""
Mostly autogenerated using Claude Sonnet 4.6
"""

from ctypes import c_char_p, c_int, c_float, c_bool, POINTER, Structure


class Position(Structure):
    _fields_ = [
        ("x", c_float),
        ("y", c_float),
    ]


class Port(Structure):
    _fields_ = [
        ("id",              c_char_p),
        ("name",            c_char_p),
        ("position_global", Position),
    ]


class Connection(Structure):
    _fields_ = [
        ("input_id",  c_char_p),
        ("output_id", c_char_p),
        ("activated", c_bool),
    ]


class AtomicBlock(Structure):
    _fields_ = [
        ("id",                   c_char_p),
        ("name",                 c_char_p),
        ("amount_input_ports",   c_int),
        ("input_ports",          POINTER(POINTER(Port))),
        ("amount_output_ports",  c_int),
        ("output_ports",         POINTER(POINTER(Port))),
        ("position",             Position),
        ("position_global",      Position),
        ("width",                c_float),
        ("height",               c_float),
    ]


class GroupBlock(Structure):
    _fields_ = [
        ("id",              c_char_p),
        ("name",            c_char_p),
        ("amount_atomics",  c_int),
        ("atomics",         POINTER(POINTER(AtomicBlock))),
        ("position",        Position),
        ("position_global", Position),
        ("width",           c_float),
        ("height",          c_float),
    ]


# Forward-declare so GlobalState can hold a pointer to Dictionary
class Dictionary(Structure):
    pass


class GlobalState(Structure):
    _fields_ = [
        ("position",           Position),
        ("amount_groups",      c_int),
        ("groups",             POINTER(POINTER(GroupBlock))),
        ("amount_atomics",     c_int),
        ("atomics",            POINTER(POINTER(AtomicBlock))),
        ("amount_connections", c_int),
        ("connections",        POINTER(POINTER(Connection))),
        ("ports",              POINTER(Dictionary)),
    ]
