name: Tests
on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./code
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-10.15 # doesn't run for free
          # - windows-2022 # can't actually run tests
        version:
          - '3.12'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: Setup Environment
        run: | 
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev
        shell: bash

      - name: Configure CMake
        working-directory: ./code/nodes-gui
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
  
      - name: Build C
        working-directory: ./code/nodes-gui
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --target nodes_library --config Release
        
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          
      - name: Install deps
        working-directory: ./code/simulator
        run: |
          python -m pip install -r requirements.txt -r requirements-dev.txt
          
      - name: Test with pytest
        working-directory: ./code
        run: python -m pytest simulator/tests/ --doctest-modules --junitxml=junit/test-results-${{ matrix.version }}.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.version }}
          working-directory: ./code/simulator
          path: junit/test-results-${{ matrix.version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
