name: Pyrefly Type Check

on:
  pull_request:
    branches: [master]
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  typecheck:
    runs-on: ubuntu-latest
    

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies and run type checking
        working-directory: ./code
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt

      - name: Install Pyrefly
        working-directory: ./code
        run: python3 -m pip install pyrefly

      - name: Run Pyrefly Type Checker
        working-directory: ./code
        run: pyrefly check

