name: Pyrefly Type Check

on:
  pull_request:
    branches: [master]
  push:
    branches:
      - master

jobs:
  typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/simulator
    

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies and run type checking
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt -r ./requirements-dev.txt

      - name: Install Pyrefly
        run: python3 -m pip install pyrefly

      - name: Run Pyrefly Type Checker
        run: pyrefly check

